spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: woainiaiwo136135
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root
# 指定日志输出
mybatis-plus:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
        logic-delete-value: 1
        logic-not-delete-value: 0